-- Dropa as tabelas na ordem correta (por causa das FKs)
DROP TABLE IF EXISTS cliente_pedido;
DROP TABLE IF EXISTS pedido_produto;
DROP TABLE IF EXISTS pedido;
DROP TABLE IF EXISTS produto;
DROP TABLE IF EXISTS cliente;

-- Criação das tabelas
CREATE TABLE IF NOT EXISTS cliente (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS produto (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    preco DECIMAL(10,2) NOT NULL CHECK (preco > 0)
    );

CREATE TABLE IF NOT EXISTS pedido (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      cliente_id BIGINT NOT NULL,
                                      data_pedido TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                      status VARCHAR(20) NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES cliente(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS pedido_produto (
                                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              produto_id BIGINT NOT NULL,
                                              pedido_id BIGINT NOT NULL,
                                              quantidade INTEGER NOT NULL CHECK (quantidade > 0),
    preco_unitario DECIMAL(10,2) NOT NULL CHECK (preco_unitario > 0),
    FOREIGN KEY (produto_id) REFERENCES produto(id) ON DELETE CASCADE,
    FOREIGN KEY (pedido_id) REFERENCES pedido(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS cliente_pedido (
                                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              id_cliente BIGINT NOT NULL,
                                              id_pedido BIGINT NOT NULL,
                                              valor_total DECIMAL(10,2) NOT NULL CHECK (valor_total > 0),
    FOREIGN KEY (id_cliente) REFERENCES cliente(id) ON DELETE CASCADE,
    FOREIGN KEY (id_pedido) REFERENCES pedido(id) ON DELETE CASCADE,
    UNIQUE(id_cliente, id_pedido)
    );